### ISSUE TITLE
Issue running deploy after installing library

### ISSUE THREAD

**Issue by jancel** [capistrano-runit/sidekiq#4]
I've successfully installed the two gems (capistrano-runit/core & capistrano-runit/sidekiq).  I'm on Debian Wheezy, running Rails 4.2. Everything goes well until I actually try to deploy new code or start the runit sidekiq service.

I've validated that I installed all of the required steps from the getting started on the core. I've also validated that the script uploaded to runit (in the application path) runs without an error.  The problem is primarily in the deploy script.  

I don't think it ever started with Capistrano.  I can log into the server and execute the installed script successfully (and it starts everything up correctly)

```
warning: /path/to/application/runit/enabled/sidekiq: unable to open supervise/ok: file does not exist
```

Here's the full application stack

```
INFO [74b1fef9] Running /usr/bin/env /usr/bin/sv stop /path/to/application/runit/enabled/sidekiq as deployment@example.com
DEBUG [74b1fef9] Command: /usr/bin/sv stop /path/to/application/runit/enabled/sidekiq
DEBUG [74b1fef9] 	warning: /path/to/application/runit/enabled/sidekiq: unable to open supervise/ok: file does not exist
cap aborted!
SSHKit::Runner::ExecuteError: Exception while executing as deployment@example.com: /usr/bin/sv stop /path/to/application/runit/enabled/sidekiq exit status: 1
/usr/bin/sv stop /path/to/application/runit/enabled/sidekiq stdout: Nothing written
/usr/bin/sv stop /path/to/application/runit/enabled/sidekiq stderr: Nothing written
/Users/jancel/.rvm/gems/ruby-2.1.2@rokkit/gems/sshkit-1.6.1/lib/sshkit/command.rb:97:in `exit_status='
/Users/jancel/.rvm/gems/ruby-2.1.2@rokkit/gems/sshkit-1.6.1/lib/sshkit/backends/netssh.rb:153:in `block (5 levels) in _execute'
/Users/jancel/.rvm/gems/ruby-2.1.2@rokkit/gems/net-ssh-2.9.2/lib/net/ssh/connection/channel.rb:551:in `call'
/Users/jancel/.rvm/gems/ruby-2.1.2@rokkit/gems/net-ssh-2.9.2/lib/net/ssh/connection/channel.rb:551:in `do_request'
/Users/jancel/.rvm/gems/ruby-2.1.2@rokkit/gems/net-ssh-2.9.2/lib/net/ssh/connection/session.rb:562:in `channel_request'
/Users/jancel/.rvm/gems/ruby-2.1.2@rokkit/gems/net-ssh-2.9.2/lib/net/ssh/connection/session.rb:466:in `dispatch_incoming_packets'
/Users/jancel/.rvm/gems/ruby-2.1.2@rokkit/gems/net-ssh-2.9.2/lib/net/ssh/connection/session.rb:222:in `preprocess'
/Users/jancel/.rvm/gems/ruby-2.1.2@rokkit/gems/net-ssh-2.9.2/lib/net/ssh/connection/session.rb:206:in `process'
/Users/jancel/.rvm/gems/ruby-2.1.2@rokkit/gems/net-ssh-2.9.2/lib/net/ssh/connection/session.rb:170:in `block in loop'
/Users/jancel/.rvm/gems/ruby-2.1.2@rokkit/gems/net-ssh-2.9.2/lib/net/ssh/connection/session.rb:170:in `loop'
/Users/jancel/.rvm/gems/ruby-2.1.2@rokkit/gems/net-ssh-2.9.2/lib/net/ssh/connection/session.rb:170:in `loop'
/Users/jancel/.rvm/gems/ruby-2.1.2@rokkit/gems/net-ssh-2.9.2/lib/net/ssh/connection/channel.rb:269:in `wait'
/Users/jancel/.rvm/gems/ruby-2.1.2@rokkit/gems/sshkit-1.6.1/lib/sshkit/backends/netssh.rb:175:in `block (3 levels) in _execute'
/Users/jancel/.rvm/gems/ruby-2.1.2@rokkit/gems/net-ssh-2.9.2/lib/net/ssh/connection/channel.rb:514:in `call'
/Users/jancel/.rvm/gems/ruby-2.1.2@rokkit/gems/net-ssh-2.9.2/lib/net/ssh/connection/channel.rb:514:in `do_open_confirmation'
/Users/jancel/.rvm/gems/ruby-2.1.2@rokkit/gems/net-ssh-2.9.2/lib/net/ssh/connection/session.rb:546:in `channel_open_confirmation'
/Users/jancel/.rvm/gems/ruby-2.1.2@rokkit/gems/net-ssh-2.9.2/lib/net/ssh/connection/session.rb:466:in `dispatch_incoming_packets'
/Users/jancel/.rvm/gems/ruby-2.1.2@rokkit/gems/net-ssh-2.9.2/lib/net/ssh/connection/session.rb:222:in `preprocess'
/Users/jancel/.rvm/gems/ruby-2.1.2@rokkit/gems/net-ssh-2.9.2/lib/net/ssh/connection/session.rb:206:in `process'
/Users/jancel/.rvm/gems/ruby-2.1.2@rokkit/gems/net-ssh-2.9.2/lib/net/ssh/connection/session.rb:170:in `block in loop'
/Users/jancel/.rvm/gems/ruby-2.1.2@rokkit/gems/net-ssh-2.9.2/lib/net/ssh/connection/session.rb:170:in `loop'
/Users/jancel/.rvm/gems/ruby-2.1.2@rokkit/gems/net-ssh-2.9.2/lib/net/ssh/connection/session.rb:170:in `loop'
/Users/jancel/.rvm/gems/ruby-2.1.2@rokkit/gems/sshkit-1.6.1/lib/sshkit/backends/netssh.rb:177:in `block (2 levels) in _execute'
/Users/jancel/.rvm/gems/ruby-2.1.2@rokkit/gems/sshkit-1.6.1/lib/sshkit/backends/netssh.rb:191:in `with_ssh'
/Users/jancel/.rvm/gems/ruby-2.1.2@rokkit/gems/sshkit-1.6.1/lib/sshkit/backends/netssh.rb:136:in `block in _execute'
/Users/jancel/.rvm/gems/ruby-2.1.2@rokkit/gems/sshkit-1.6.1/lib/sshkit/backends/netssh.rb:133:in `tap'
/Users/jancel/.rvm/gems/ruby-2.1.2@rokkit/gems/sshkit-1.6.1/lib/sshkit/backends/netssh.rb:133:in `_execute'
/Users/jancel/.rvm/gems/ruby-2.1.2@rokkit/gems/sshkit-1.6.1/lib/sshkit/backends/netssh.rb:66:in `execute'
/Users/jancel/.rvm/gems/ruby-2.1.2@rokkit/bundler/gems/core-d8ff0f16fb22/lib/capistrano/runit.rb:123:in `runit_execute_command'
/Users/jancel/.rvm/gems/ruby-2.1.2@rokkit/bundler/gems/core-d8ff0f16fb22/lib/capistrano/runit.rb:98:in `block in stop_service'
/Users/jancel/.rvm/gems/ruby-2.1.2@rokkit/gems/sshkit-1.6.1/lib/sshkit/backends/netssh.rb:54:in `instance_exec'
/Users/jancel/.rvm/gems/ruby-2.1.2@rokkit/gems/sshkit-1.6.1/lib/sshkit/backends/netssh.rb:54:in `run'
/Users/jancel/.rvm/gems/ruby-2.1.2@rokkit/gems/sshkit-1.6.1/lib/sshkit/runners/parallel.rb:13:in `block (2 levels) in execute'
SSHKit::Command::Failed: /usr/bin/sv stop /path/to/application/runit/enabled/sidekiq exit status: 1
/usr/bin/sv stop /path/to/application/runit/enabled/sidekiq stdout: Nothing written
/usr/bin/sv stop /path/to/application/runit/enabled/sidekiq stderr: Nothing written
/Users/jancel/.rvm/gems/ruby-2.1.2@rokkit/gems/sshkit-1.6.1/lib/sshkit/command.rb:97:in `exit_status='
/Users/jancel/.rvm/gems/ruby-2.1.2@rokkit/gems/sshkit-1.6.1/lib/sshkit/backends/netssh.rb:153:in `block (5 levels) in _execute'
/Users/jancel/.rvm/gems/ruby-2.1.2@rokkit/gems/net-ssh-2.9.2/lib/net/ssh/connection/channel.rb:551:in `call'
/Users/jancel/.rvm/gems/ruby-2.1.2@rokkit/gems/net-ssh-2.9.2/lib/net/ssh/connection/channel.rb:551:in `do_request'
/Users/jancel/.rvm/gems/ruby-2.1.2@rokkit/gems/net-ssh-2.9.2/lib/net/ssh/connection/session.rb:562:in `channel_request'
/Users/jancel/.rvm/gems/ruby-2.1.2@rokkit/gems/net-ssh-2.9.2/lib/net/ssh/connection/session.rb:466:in `dispatch_incoming_packets'
/Users/jancel/.rvm/gems/ruby-2.1.2@rokkit/gems/net-ssh-2.9.2/lib/net/ssh/connection/session.rb:222:in `preprocess'
/Users/jancel/.rvm/gems/ruby-2.1.2@rokkit/gems/net-ssh-2.9.2/lib/net/ssh/connection/session.rb:206:in `process'
/Users/jancel/.rvm/gems/ruby-2.1.2@rokkit/gems/net-ssh-2.9.2/lib/net/ssh/connection/session.rb:170:in `block in loop'
/Users/jancel/.rvm/gems/ruby-2.1.2@rokkit/gems/net-ssh-2.9.2/lib/net/ssh/connection/session.rb:170:in `loop'
/Users/jancel/.rvm/gems/ruby-2.1.2@rokkit/gems/net-ssh-2.9.2/lib/net/ssh/connection/session.rb:170:in `loop'
/Users/jancel/.rvm/gems/ruby-2.1.2@rokkit/gems/net-ssh-2.9.2/lib/net/ssh/connection/channel.rb:269:in `wait'
/Users/jancel/.rvm/gems/ruby-2.1.2@rokkit/gems/sshkit-1.6.1/lib/sshkit/backends/netssh.rb:175:in `block (3 levels) in _execute'
/Users/jancel/.rvm/gems/ruby-2.1.2@rokkit/gems/net-ssh-2.9.2/lib/net/ssh/connection/channel.rb:514:in `call'
/Users/jancel/.rvm/gems/ruby-2.1.2@rokkit/gems/net-ssh-2.9.2/lib/net/ssh/connection/channel.rb:514:in `do_open_confirmation'
/Users/jancel/.rvm/gems/ruby-2.1.2@rokkit/gems/net-ssh-2.9.2/lib/net/ssh/connection/session.rb:546:in `channel_open_confirmation'
/Users/jancel/.rvm/gems/ruby-2.1.2@rokkit/gems/net-ssh-2.9.2/lib/net/ssh/connection/session.rb:466:in `dispatch_incoming_packets'
/Users/jancel/.rvm/gems/ruby-2.1.2@rokkit/gems/net-ssh-2.9.2/lib/net/ssh/connection/session.rb:222:in `preprocess'
/Users/jancel/.rvm/gems/ruby-2.1.2@rokkit/gems/net-ssh-2.9.2/lib/net/ssh/connection/session.rb:206:in `process'
/Users/jancel/.rvm/gems/ruby-2.1.2@rokkit/gems/net-ssh-2.9.2/lib/net/ssh/connection/session.rb:170:in `block in loop'
/Users/jancel/.rvm/gems/ruby-2.1.2@rokkit/gems/net-ssh-2.9.2/lib/net/ssh/connection/session.rb:170:in `loop'
/Users/jancel/.rvm/gems/ruby-2.1.2@rokkit/gems/net-ssh-2.9.2/lib/net/ssh/connection/session.rb:170:in `loop'
/Users/jancel/.rvm/gems/ruby-2.1.2@rokkit/gems/sshkit-1.6.1/lib/sshkit/backends/netssh.rb:177:in `block (2 levels) in _execute'
/Users/jancel/.rvm/gems/ruby-2.1.2@rokkit/gems/sshkit-1.6.1/lib/sshkit/backends/netssh.rb:191:in `with_ssh'
/Users/jancel/.rvm/gems/ruby-2.1.2@rokkit/gems/sshkit-1.6.1/lib/sshkit/backends/netssh.rb:136:in `block in _execute'
/Users/jancel/.rvm/gems/ruby-2.1.2@rokkit/gems/sshkit-1.6.1/lib/sshkit/backends/netssh.rb:133:in `tap'
/Users/jancel/.rvm/gems/ruby-2.1.2@rokkit/gems/sshkit-1.6.1/lib/sshkit/backends/netssh.rb:133:in `_execute'
/Users/jancel/.rvm/gems/ruby-2.1.2@rokkit/gems/sshkit-1.6.1/lib/sshkit/backends/netssh.rb:66:in `execute'
/Users/jancel/.rvm/gems/ruby-2.1.2@rokkit/bundler/gems/core-d8ff0f16fb22/lib/capistrano/runit.rb:123:in `runit_execute_command'
/Users/jancel/.rvm/gems/ruby-2.1.2@rokkit/bundler/gems/core-d8ff0f16fb22/lib/capistrano/runit.rb:98:in `block in stop_service'
/Users/jancel/.rvm/gems/ruby-2.1.2@rokkit/gems/sshkit-1.6.1/lib/sshkit/backends/netssh.rb:54:in `instance_exec'
/Users/jancel/.rvm/gems/ruby-2.1.2@rokkit/gems/sshkit-1.6.1/lib/sshkit/backends/netssh.rb:54:in `run'
/Users/jancel/.rvm/gems/ruby-2.1.2@rokkit/gems/sshkit-1.6.1/lib/sshkit/runners/parallel.rb:13:in `block (2 levels) in execute'
Tasks: TOP => runit:sidekiq:stop
```

**Comment by antage** [comment]
@jancel It seems `runsvdir /path/to/application/runit/enabled/` isn't running.

**Comment by simonoff** [comment]
Yes, because he doing first deploy. Need to add checking of pid file on stop too.
Or would be better to add checking state of service and based on it doing job.

**Comment by jancel** [comment]
That is correct. This happens on first deploy, and every other attempt I've tried I started the service manually (which I know isn't the expected way) and set to run default hooks (false) in my deploy.rb to successfully launch my code.

**Comment by antage** [comment]
@simonoff It's strange because `stop_service` checks pid file by default: https://github.com/capistrano-runit/core/blob/master/lib/capistrano/runit.rb#L97

**Comment by antage** [comment]
I think a reason of issue is staled pid file after manual start-stop service.

**Comment by simonoff** [comment]
@antage so may be better to check both? pid file if it was running manually and service status if it was running through runit? What do you think?

**Comment by jancel** [comment]
I get a very similar issue whenever I try to do anything (quiet, stop, start, restart).  Is there a way to start fresh, like: 1. stop service, 2. delete files x, y, z, 3. try running a, b, c 4. Report.  After the first fail, I gave it several goes to get it running; it's very possible I screwed something up, but what.

**Comment by jancel** [comment]
+1 @simonoff I think that would be a pretty robust solution if it's possible. I like it when things just work.

**Comment by antage** [comment]
I has added additional checking in `stop_service`: capistrano-runit/core@3110826f1b39e3a8eeddc26f3ba9802de22eff6a

**Comment by jancel** [comment]
This may or not be related. I'll defer because I'm just digging into the code, but the stop runs fine now. It reports that 'sidekiq' isn't running.  

I updated the core gem, is there a way to uninstall the server dependencies and give it a fresh go?

The new error is now on start: 
```
INFO [c59f2729] Running /usr/bin/env /usr/bin/sv start /path/to/application/runit/enabled/sidekiq as deployment@example.com
DEBUG [c59f2729] Command: /usr/bin/sv start /path/to/application/runit/enabled/sidekiq
DEBUG [c59f2729]  warning: /path/to/application/runit/enabled/sidekiq: unable to open supervise/ok: file does not exist
cap aborted!
SSHKit::Runner::ExecuteError: Exception while executing as deployment@example.com: /usr/bin/sv start /path/to/application/runit/enabled/sidekiq exit status: 1
/usr/bin/sv start /path/to/application/runit/enabled/sidekiq stdout: Nothing written
/usr/bin/sv start /path/to/application/runit/enabled/sidekiq stderr: Nothing written
/Users/jancel/.rvm/gems/ruby-2.1.2@rokkit/gems/sshkit-1.6.1/lib/sshkit/command.rb:97:in `exit_status='
/Users/jancel/.rvm/gems/ruby-2.1.2@rokkit/gems/sshkit-1.6.1/lib/sshkit/backends/netssh.rb:153:in `block (5 levels) in _execute'
/Users/jancel/.rvm/gems/ruby-2.1.2@rokkit/gems/net-ssh-2.9.2/lib/net/ssh/connection/channel.rb:551:in `call'
/Users/jancel/.rvm/gems/ruby-2.1.2@rokkit/gems/net-ssh-2.9.2/lib/net/ssh/connection/channel.rb:551:in `do_request'
/Users/jancel/.rvm/gems/ruby-2.1.2@rokkit/gems/net-ssh-2.9.2/lib/net/ssh/connection/session.rb:562:in `channel_request'
/Users/jancel/.rvm/gems/ruby-2.1.2@rokkit/gems/net-ssh-2.9.2/lib/net/ssh/connection/session.rb:466:in `dispatch_incoming_packets'
/Users/jancel/.rvm/gems/ruby-2.1.2@rokkit/gems/net-ssh-2.9.2/lib/net/ssh/connection/session.rb:222:in `preprocess'
/Users/jancel/.rvm/gems/ruby-2.1.2@rokkit/gems/net-ssh-2.9.2/lib/net/ssh/connection/session.rb:206:in `process'
/Users/jancel/.rvm/gems/ruby-2.1.2@rokkit/gems/net-ssh-2.9.2/lib/net/ssh/connection/session.rb:170:in `block in loop'
/Users/jancel/.rvm/gems/ruby-2.1.2@rokkit/gems/net-ssh-2.9.2/lib/net/ssh/connection/session.rb:170:in `loop'
/Users/jancel/.rvm/gems/ruby-2.1.2@rokkit/gems/net-ssh-2.9.2/lib/net/ssh/connection/session.rb:170:in `loop'
/Users/jancel/.rvm/gems/ruby-2.1.2@rokkit/gems/net-ssh-2.9.2/lib/net/ssh/connection/channel.rb:269:in `wait'
/Users/jancel/.rvm/gems/ruby-2.1.2@rokkit/gems/sshkit-1.6.1/lib/sshkit/backends/netssh.rb:175:in `block (3 levels) in _execute'
/Users/jancel/.rvm/gems/ruby-2.1.2@rokkit/gems/net-ssh-2.9.2/lib/net/ssh/connection/channel.rb:514:in `call'
/Users/jancel/.rvm/gems/ruby-2.1.2@rokkit/gems/net-ssh-2.9.2/lib/net/ssh/connection/channel.rb:514:in `do_open_confirmation'
/Users/jancel/.rvm/gems/ruby-2.1.2@rokkit/gems/net-ssh-2.9.2/lib/net/ssh/connection/session.rb:546:in `channel_open_confirmation'
/Users/jancel/.rvm/gems/ruby-2.1.2@rokkit/gems/net-ssh-2.9.2/lib/net/ssh/connection/session.rb:466:in `dispatch_incoming_packets'
/Users/jancel/.rvm/gems/ruby-2.1.2@rokkit/gems/net-ssh-2.9.2/lib/net/ssh/connection/session.rb:222:in `preprocess'
/Users/jancel/.rvm/gems/ruby-2.1.2@rokkit/gems/net-ssh-2.9.2/lib/net/ssh/connection/session.rb:206:in `process'
/Users/jancel/.rvm/gems/ruby-2.1.2@rokkit/gems/net-ssh-2.9.2/lib/net/ssh/connection/session.rb:170:in `block in loop'
/Users/jancel/.rvm/gems/ruby-2.1.2@rokkit/gems/net-ssh-2.9.2/lib/net/ssh/connection/session.rb:170:in `loop'
/Users/jancel/.rvm/gems/ruby-2.1.2@rokkit/gems/net-ssh-2.9.2/lib/net/ssh/connection/session.rb:170:in `loop'
/Users/jancel/.rvm/gems/ruby-2.1.2@rokkit/gems/sshkit-1.6.1/lib/sshkit/backends/netssh.rb:177:in `block (2 levels) in _execute'
/Users/jancel/.rvm/gems/ruby-2.1.2@rokkit/gems/sshkit-1.6.1/lib/sshkit/backends/netssh.rb:191:in `with_ssh'
/Users/jancel/.rvm/gems/ruby-2.1.2@rokkit/gems/sshkit-1.6.1/lib/sshkit/backends/netssh.rb:136:in `block in _execute'
/Users/jancel/.rvm/gems/ruby-2.1.2@rokkit/gems/sshkit-1.6.1/lib/sshkit/backends/netssh.rb:133:in `tap'
/Users/jancel/.rvm/gems/ruby-2.1.2@rokkit/gems/sshkit-1.6.1/lib/sshkit/backends/netssh.rb:133:in `_execute'
/Users/jancel/.rvm/gems/ruby-2.1.2@rokkit/gems/sshkit-1.6.1/lib/sshkit/backends/netssh.rb:66:in `execute'
/Users/jancel/.rvm/gems/ruby-2.1.2@rokkit/bundler/gems/core-3110826f1b39/lib/capistrano/runit.rb:142:in `runit_execute_command'
/Users/jancel/.rvm/gems/ruby-2.1.2@rokkit/bundler/gems/core-3110826f1b39/lib/capistrano/runit.rb:104:in `block in start_service'
/Users/jancel/.rvm/gems/ruby-2.1.2@rokkit/gems/sshkit-1.6.1/lib/sshkit/backends/netssh.rb:54:in `instance_exec'
/Users/jancel/.rvm/gems/ruby-2.1.2@rokkit/gems/sshkit-1.6.1/lib/sshkit/backends/netssh.rb:54:in `run'
/Users/jancel/.rvm/gems/ruby-2.1.2@rokkit/gems/sshkit-1.6.1/lib/sshkit/runners/parallel.rb:13:in `block (2 levels) in execute'
SSHKit::Command::Failed: /usr/bin/sv start /path/to/application/runit/enabled/sidekiq exit status: 1
/usr/bin/sv start /path/to/application/runit/enabled/sidekiq stdout: Nothing written
/usr/bin/sv start /path/to/application/runit/enabled/sidekiq stderr: Nothing written
/Users/jancel/.rvm/gems/ruby-2.1.2@rokkit/gems/sshkit-1.6.1/lib/sshkit/command.rb:97:in `exit_status='
/Users/jancel/.rvm/gems/ruby-2.1.2@rokkit/gems/sshkit-1.6.1/lib/sshkit/backends/netssh.rb:153:in `block (5 levels) in _execute'
/Users/jancel/.rvm/gems/ruby-2.1.2@rokkit/gems/net-ssh-2.9.2/lib/net/ssh/connection/channel.rb:551:in `call'
/Users/jancel/.rvm/gems/ruby-2.1.2@rokkit/gems/net-ssh-2.9.2/lib/net/ssh/connection/channel.rb:551:in `do_request'
/Users/jancel/.rvm/gems/ruby-2.1.2@rokkit/gems/net-ssh-2.9.2/lib/net/ssh/connection/session.rb:562:in `channel_request'
/Users/jancel/.rvm/gems/ruby-2.1.2@rokkit/gems/net-ssh-2.9.2/lib/net/ssh/connection/session.rb:466:in `dispatch_incoming_packets'
/Users/jancel/.rvm/gems/ruby-2.1.2@rokkit/gems/net-ssh-2.9.2/lib/net/ssh/connection/session.rb:222:in `preprocess'
/Users/jancel/.rvm/gems/ruby-2.1.2@rokkit/gems/net-ssh-2.9.2/lib/net/ssh/connection/session.rb:206:in `process'
/Users/jancel/.rvm/gems/ruby-2.1.2@rokkit/gems/net-ssh-2.9.2/lib/net/ssh/connection/session.rb:170:in `block in loop'
/Users/jancel/.rvm/gems/ruby-2.1.2@rokkit/gems/net-ssh-2.9.2/lib/net/ssh/connection/session.rb:170:in `loop'
/Users/jancel/.rvm/gems/ruby-2.1.2@rokkit/gems/net-ssh-2.9.2/lib/net/ssh/connection/session.rb:170:in `loop'
/Users/jancel/.rvm/gems/ruby-2.1.2@rokkit/gems/net-ssh-2.9.2/lib/net/ssh/connection/channel.rb:269:in `wait'
/Users/jancel/.rvm/gems/ruby-2.1.2@rokkit/gems/sshkit-1.6.1/lib/sshkit/backends/netssh.rb:175:in `block (3 levels) in _execute'
/Users/jancel/.rvm/gems/ruby-2.1.2@rokkit/gems/net-ssh-2.9.2/lib/net/ssh/connection/channel.rb:514:in `call'
/Users/jancel/.rvm/gems/ruby-2.1.2@rokkit/gems/net-ssh-2.9.2/lib/net/ssh/connection/channel.rb:514:in `do_open_confirmation'
/Users/jancel/.rvm/gems/ruby-2.1.2@rokkit/gems/net-ssh-2.9.2/lib/net/ssh/connection/session.rb:546:in `channel_open_confirmation'
/Users/jancel/.rvm/gems/ruby-2.1.2@rokkit/gems/net-ssh-2.9.2/lib/net/ssh/connection/session.rb:466:in `dispatch_incoming_packets'
/Users/jancel/.rvm/gems/ruby-2.1.2@rokkit/gems/net-ssh-2.9.2/lib/net/ssh/connection/session.rb:222:in `preprocess'
/Users/jancel/.rvm/gems/ruby-2.1.2@rokkit/gems/net-ssh-2.9.2/lib/net/ssh/connection/session.rb:206:in `process'
/Users/jancel/.rvm/gems/ruby-2.1.2@rokkit/gems/net-ssh-2.9.2/lib/net/ssh/connection/session.rb:170:in `block in loop'
/Users/jancel/.rvm/gems/ruby-2.1.2@rokkit/gems/net-ssh-2.9.2/lib/net/ssh/connection/session.rb:170:in `loop'
/Users/jancel/.rvm/gems/ruby-2.1.2@rokkit/gems/net-ssh-2.9.2/lib/net/ssh/connection/session.rb:170:in `loop'
/Users/jancel/.rvm/gems/ruby-2.1.2@rokkit/gems/sshkit-1.6.1/lib/sshkit/backends/netssh.rb:177:in `block (2 levels) in _execute'
/Users/jancel/.rvm/gems/ruby-2.1.2@rokkit/gems/sshkit-1.6.1/lib/sshkit/backends/netssh.rb:191:in `with_ssh'
/Users/jancel/.rvm/gems/ruby-2.1.2@rokkit/gems/sshkit-1.6.1/lib/sshkit/backends/netssh.rb:136:in `block in _execute'
/Users/jancel/.rvm/gems/ruby-2.1.2@rokkit/gems/sshkit-1.6.1/lib/sshkit/backends/netssh.rb:133:in `tap'
/Users/jancel/.rvm/gems/ruby-2.1.2@rokkit/gems/sshkit-1.6.1/lib/sshkit/backends/netssh.rb:133:in `_execute'
/Users/jancel/.rvm/gems/ruby-2.1.2@rokkit/gems/sshkit-1.6.1/lib/sshkit/backends/netssh.rb:66:in `execute'
/Users/jancel/.rvm/gems/ruby-2.1.2@rokkit/bundler/gems/core-3110826f1b39/lib/capistrano/runit.rb:142:in `runit_execute_command'
/Users/jancel/.rvm/gems/ruby-2.1.2@rokkit/bundler/gems/core-3110826f1b39/lib/capistrano/runit.rb:104:in `block in start_service'
/Users/jancel/.rvm/gems/ruby-2.1.2@rokkit/gems/sshkit-1.6.1/lib/sshkit/backends/netssh.rb:54:in `instance_exec'
/Users/jancel/.rvm/gems/ruby-2.1.2@rokkit/gems/sshkit-1.6.1/lib/sshkit/backends/netssh.rb:54:in `run'
/Users/jancel/.rvm/gems/ruby-2.1.2@rokkit/gems/sshkit-1.6.1/lib/sshkit/runners/parallel.rb:13:in `block (2 levels) in execute'
Tasks: TOP => runit:sidekiq:start
```

**Comment by antage** [comment]
@jancel It's more weird. Runit must create `supervise/ok` file. Are you sure `runsvdir` is running?

**Comment by jancel** [comment]
I went in and status' the app and this is what I got. Is there an issue with sudo versus non-sudo.  I typically install things as the user, but in this case, I've only followed the instructions.

```
deployment@example:~/application/shared/config$ sv status runsvdir-rokkit-rails
warning: runsvdir-rokkit-rails: unable to open supervise/ok: access denied
deployment@example:~/application/shared/config$ sudo sv status runsvdir-rokkit-rails
run: runsvdir-rokkit-rails: (pid 5255) 8170s; down: log: 0s, normally up, want up
deployment@example:~/application/shared/config$
```

**Comment by jancel** [comment]
On further inspection, I also tried the command that was failing.

```
deployment@example:/path/to/application/shared/config$ sv start /path/to/application /runit/enabled/sidekiq
warning: /path/to/application /runit/enabled/sidekiq: unable to open supervise/ok: file does not exist
deployment@example:/path/to/application/shared/config$ sudo sv start /path/to/application/runit/enabled/sidekiq
warning: /path/to/application/runit/enabled/sidekiq: unable to open supervise/ok: file does not exist
```

**Comment by jancel** [comment]
I removed the runit directory under my application, starting from fresh, I run "runit:sidekiq:setup" and I get: mkdir: cannot create directory `/path/to/application/runit/available/sidekiq': No such file or directory.

So I ran: "runit:setup" (success)
Then "runit:sidekiq:setup" (success)
Then "runit:sidekiq:enable" (success)

Trying any of these commands (start/restart) both produce errors.  Also, the stop command reports 'not running' and the quiet command executed silently with no output.

**Comment by simonoff** [comment]
@jancel did you doing all stuff in https://github.com/capistrano-runit/core#runit-setup?

**Comment by jancel** [comment]
Indeed. I left those original changes in tact.  I actually verified that they are all in there per the instructions each piece. Including search path as my sv process was/is in /usr/bin, neither of the sbin dirs.

**Comment by jancel** [comment]
Further information.  It appears that there is an issue with vdir-application in the first service below.  I am looking for it, a typo or creating the other directory.  Is this a core thing?

```
root@picturethis:/var/log# ps -ef | grep runsv
root      3828     1  0 15:53 ?        00:00:01 runsvdir -P /etc/service log: vdir-application: fatal: unable to start log/./run: exec format error runsv runsvdir-application: fatal: unable to start log/./run: exec format error runsv runsvdir-application: fatal: unable to start log/./run: exec format error runsv runsvdir-application: fatal: unable to start log/./run: exec format error runsv runsvdir-application: fatal: unable to start log/./run: exec format error
root      3829  3828  0 15:53 ?        00:00:08 runsv runsvdir-application
root      5255  3829  0 16:02 ?        00:00:00 chpst -udeployment:deployment -e /path/to/application/shared/runit/.env runsvdir /path/to/application/shared/runit/enabled
root     26722 26497  0 19:01 pts/0    00:00:00 grep runsv
```

**Comment by antage** [comment]
@jancel Does `/etc/sv/runsvdir-application/log/run` have executable bit in permissions? Can you run it manually? Can you run `/etc/sv/runsvdir-application/run` manually?

**Comment by antage** [comment]
@jancel 
> It appears that there is an issue with vdir-application in the first service below.

`vdir-application` is just truncated `runsvdir-application` text.

**Comment by jancel** [comment]
I see that but I don't see why it's truncated. Running the run file it was
looking for stuff in the shared for and I believe this formula doesn't use
the shared for. It uses its own run it. After I cleared that issue the run
file worked and so too did a sb command for restart. I'll hit it from cap
later today.

On Wednesday, January 21, 2015, Anton Ageev <notifications@github.com>
wrote:

> @jancel <https://github.com/jancel> It seems runsvdir
> /path/to/application/runit/enabled/ isn't running.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/capistrano-runit/sidekiq/issues/4#issuecomment-70793836>
> .
>


-- 
Jeff Ancel

(314) 703-8829 - Main

www.jeffancel.com

**Comment by simonoff** [comment]
@jancel so it still not working or working?

**Comment by hd-deman** [comment]
working
