### ISSUE TITLE
invalid option: --index

### ISSUE THREAD

**Issue by vesh95** [capistrano-runit/sidekiq#6]
When I run deploy, via capistrano I get an error:
```
invalid option: --index
/home/eduard/.rvm/gems/ruby-2.5.5@qna/gems/sidekiq-6.0.5/lib/sidekiq/cli.rb:291:in `parse_options'
/home/eduard/.rvm/gems/ruby-2.5.5@qna/gems/sidekiq-6.0.5/lib/sidekiq/cli.rb:205:in `setup_options'
/home/eduard/.rvm/gems/ruby-2.5.5@qna/gems/sidekiq-6.0.5/lib/sidekiq/cli.rb:24:in `parse'
/home/eduard/.rvm/gems/ruby-2.5.5@qna/gems/sidekiq-6.0.5/bin/sidekiq:11:in `<top (required)>'
/home/eduard/.rvm/gems/ruby-2.5.5@qna/bin/sidekiq:23:in `load'
/home/eduard/.rvm/gems/ruby-2.5.5@qna/bin/sidekiq:23:in `<main>'
/home/eduard/.rvm/gems/ruby-2.5.5@qna/bin/ruby_executable_hooks:24:in `eval'
/home/eduard/.rvm/gems/ruby-2.5.5@qna/bin/ruby_executable_hooks:24:in `<main>'
```
I use capistrano-sidekiq gem

**Comment by simonoff** [comment]
There is no support for sidekiq 6.x yet
